import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import { SiteHeader } from "@/components/site-header";
import { SidebarInset } from "@/components/ui/sidebar";
import ClientSiteHeader from "@/components/client-site-header";

export const metadata: Metadata = {
  title: "Driver Swap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
              <SidebarInset>

                {/* SiteHeader needs to read localStorage; mount a client wrapper so this server component doesn't access window */}
                {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
                {/* ClientSiteHeader reads localStorage on the client and conditionally renders SiteHeader */}
                {/* Importing dynamically to keep layout lean */}
                <React.Suspense fallback={null}>
                  <ClientSiteHeader />
                </React.Suspense>

        
        {children}
              </SidebarInset>

      </body>
    </html>
  );
}
