import type { Metadata } from "next";
import { Cairo } from 'next/font/google'
import "./globals.css";
import React from "react";
import { SiteHeader } from "@/components/site-header";
import { SidebarInset } from "@/components/ui/sidebar";
import ClientSiteHeader from "@/components/client-site-header";

export const metadata: Metadata = {
  title: "Driver Swap",
  description: "Generated by create next app",
};

const cairo = Cairo({
  subsets: ['arabic', 'latin'],
  weight: ['400', '700'],
  variable: '--font-cairo'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cairo.className} antialiased`}>
              <SidebarInset>

                {/* SiteHeader needs to read localStorage; mount a client wrapper so this server component doesn't access window */}
                {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
                {/* ClientSiteHeader reads localStorage on the client and conditionally renders SiteHeader */}
                {/* Importing dynamically to keep layout lean */}
                <React.Suspense fallback={null}>
                  <ClientSiteHeader />
                </React.Suspense>

        
        {children}
              </SidebarInset>

      </body>
    </html>
  );
}
